### PR TITLE
Simplify and speed up search code

### PR DESCRIPTION
**Pull request by PeterBloomfield**
```
* R/code_generic.R (find.plan): simplify search code for
  binomial, hypergeometric, and Poisson cases; new code runs in
  roughly 50% of the time.
```

### CODE REVIEW

**Comment by PeterBloomfield** [comment]
Hi Andreas,

Glad to see the new repo! This commit is the streamlined find.plan code. No documentation required.

Best,

Peter

**Comment by PeterBloomfield** [comment]
R-code to test timing and correctness of the streamlined code.

[find-plan-test-R.txt](https://github.com/andreaskiermeier/AcceptanceSampling/files/41231/find-plan-test-R.txt)

**Comment by andreaskiermeier** [comment]
Hi Peter,
have run through the test file several times with different PRP and CRP values. The first time I ran the code I got about a 50% reduction in time. On the second, third and forth run the difference was minimal (see top of the updated file). Note that on the last run I used the same PRP and CRP as for the first run.

The upside is that the output is the same and there is maybe a potential for a reduction in execution time ... so if nothing else, at least it's not worse. In addition, the code is simplified, though I found it harder to follow.

Thoughts?

[find-plan-test-R.txt](https://github.com/andreaskiermeier/AcceptanceSampling/files/41337/find-plan-test-R.txt)

**Comment by PeterBloomfield** [comment]
Hi Andreas,

OK, the timings are weird! Measuring performance in R is clearly delicate...

I added "print(find.plan)" immediately before the last "detach(2)", i.e. after installing the "old" repo, and the definition is still the new one! Somehow, detaching the library, reinstalling it, then re-attaching it, seems to pick up the previously installed version. I'm not clear about exactly what install_github does!

Best,

Peter

**Comment by PeterBloomfield** [comment]
The second commit gives the default rejection numbers in double-sampling.

**Comment by PeterBloomfield** [comment]
I retested the find.plan code by making find.plan.new and find.plan.old and installing from a single local code tree, so that I was sure which code was being executed! The timings are identical--I have no idea where that earlier factor of 2 was coming from :(

Your call whether to simplify or just keep the existing code--there's no difference in performance.

**Comment by andreaskiermeier** [comment]
Thanks Peter.
Have merged into master - I did like the succinct style.

**Pull request merged**
